---
- name: Assert that prerequisites exist
  tags: rpmforge
  assert:
    that:
      - rpmforge_pkg is defined
      - rpmforge_ver is defined
      - rpmforge_rel is defined
      - rpmforge_baseurl is defined

- name: Generate random package name
  tags: rpmforge
  command: mktemp -u --suffix .rpm
  register: rpmforge_mktemp

- name: Fetch {{ rpmforge_pkg }} to temporary destination
  tags: rpmforge
  get_url:
    url: "{{ rpmforge_fetch }}"
    dest: "{{ rpmforge_mktemp.stdout }}"
  register: rpmforge_get_url
  when: rpmforge_mktemp|success

- name: Ensure that the {{ rpmforge_pkg }} package is installed
  tags: rpmforge
  yum:
    name: "{{ item }}"
    state: present
  register: rpmforge_yum
  with_items: "{{ rpmforge_mktemp.stdout }}"
  when: rpmforge_get_url|success

- name: Applying {{ rpmforge_pkg }} configurations
  tags: rpmforge
  template:
    src: rpmforge.repo.j2
    dest: /etc/yum.repos.d/rpmforge.repo
    owner: root
    group: root
    mode: 0644
  when: rpmforge_yum|success

- name: Prune temporary package from the filesystem
  tags: rpmforge
  file:
    path: "{{ rpmforge_mktemp.stdout }}"
    state: absent
  when:
    - rpmforge_mktemp|success
    - rpmforge_yum|success
...
