---
- name: Assert that the prerequisites are defined
  tags: rpmforge
  assert:
    that:
      - rpmforge_pkg is defined
      - rpmforge_ver is defined
      - rpmforge_rel is defined
      - rpmforge_baseurl is defined

- name: Generating temporary filename via mktemp
  tags: rpmforge
  command: mktemp -u --suffix .rpm
  register: rpmforge_mktemp

- name: Downloading package to temporary location
  tags: rpmforge
  get_url:
    dest: "{{ rpmforge_mktemp.stdout }}"
    url: "{{ rpmforge_fetch }}"
  register: rpmforge_get_url
  when: rpmforge_mktemp|success

- name: Ensure that the rpmforge-release package is installed
  tags: rpmforge
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: rpmforge_yum
  with_items: "{{ rpmforge_mktemp.stdout }}"
  when: rpmforge_get_url|success

- name: Applying rpmforge repository configurations
  tags: rpmforge
  become: true
  template:
    src: rpmforge.repo.j2
    dest: /etc/yum.repos.d/rpmforge.repo
    owner: root
    group: root
    mode: 0644
  when: rpmforge_yum|success

- name: Ensure that the RepoForge GPG keys are installed
  tags: rpmforge
  become: true
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmforge-dag
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmforge-fabian

- name: Purging temporary package from filesystem
  tags: rpmforge
  file:
    path: "{{ rpmforge_mktemp.stdout }}"
    state: absent
  when:
    - rpmforge_mktemp|success
    - rpmforge_yum|success
...
